export const countries = [
  { name: "Afeganistão", flag: "🇦🇫" },
  { name: "África do Sul", flag: "🇿🇦" },
  { name: "Albânia", flag: "🇦🇱" },
  { name: "Alemanha", flag: "🇩🇪" },
  { name: "Andorra", flag: "🇦🇩" },
  { name: "Angola", flag: "🇦🇴" },
  { name: "Antígua e Barbuda", flag: "🇦🇬" },
  { name: "Arábia Saudita", flag: "🇸🇦" },
  { name: "Argélia", flag: "🇩🇿" },
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Armênia", flag: "🇦🇲" },
  { name: "Austrália", flag: "🇦🇺" },
  { name: "Áustria", flag: "🇦🇹" },
  { name: "Azerbaijão", flag: "🇦🇿" },
  { name: "Bahamas", flag: "🇧🇸" },
  { name: "Bahrein", flag: "🇧🇭" },
  { name: "Bangladesh", flag: "🇧🇩" },
  { name: "Barbados", flag: "🇧🇧" },
  { name: "Bélgica", flag: "🇧🇪" },
  { name: "Belize", flag: "🇧🇿" },
  { name: "Benim", flag: "🇧🇯" },
  { name: "Bielorrússia", flag: "🇧🇾" },
  { name: "Bolívia", flag: "🇧🇴" },
  { name: "Bósnia e Herzegovina", flag: "🇧🇦" },
  { name: "Botsuana", flag: "🇧🇼" },
  { name: "Brasil", flag: "🇧🇷" },
  { name: "Brunei", flag: "🇧🇳" },
  { name: "Bulgária", flag: "🇧🇬" },
  { name: "Burquina Faso", flag: "🇧🇫" },
  { name: "Burundi", flag: "🇧🇮" },
  { name: "Butão", flag: "🇧🇹" },
  { name: "Cabo Verde", flag: "🇨🇻" },
  { name: "Camarões", flag: "🇨🇲" },
  { name: "Camboja", flag: "🇰🇭" },
  { name: "Canadá", flag: "🇨🇦" },
  { name: "Catar", flag: "🇶🇦" },
  { name: "Cazaquistão", flag: "🇰🇿" },
  { name: "Chade", flag: "🇹🇩" },
  { name: "Chile", flag: "🇨🇱" },
  { name: "China", flag: "🇨🇳" },
  { name: "Chipre", flag: "🇨🇾" },
  { name: "Colômbia", flag: "🇨🇴" },
  { name: "Comores", flag: "🇰🇲" },
  { name: "Coreia do Norte", flag: "🇰🇵" },
  { name: "Coreia do Sul", flag: "🇰🇷" },
  { name: "Costa do Marfim", flag: "🇨🇮" },
  { name: "Costa Rica", flag: "🇨🇷" },
  { name: "Croácia", flag: "🇭🇷" },
  { name: "Cuba", flag: "🇨🇺" },
  { name: "Dinamarca", flag: "🇩🇰" },
  { name: "Djibuti", flag: "🇩🇯" },
  { name: "Dominica", flag: "🇩🇲" },
  { name: "Egito", flag: "🇪🇬" },
  { name: "El Salvador", flag: "🇸🇻" },
  { name: "Emirados Árabes Unidos", flag: "🇦🇪" },
  { name: "Equador", flag: "🇪🇨" },
  { name: "Eritreia", flag: "🇪🇷" },
  { name: "Eslováquia", flag: "🇸🇰" },
  { name: "Eslovênia", flag: "🇸🇮" },
  { name: "Espanha", flag: "🇪🇸" },
  { name: "Estados Unidos", flag: "🇺🇸" },
  { name: "Estônia", flag: "🇪🇪" },
  { name: "Eswatini", flag: "🇸🇿" },
  { name: "Etiópia", flag: "🇪🇹" },
  { name: "Fiji", flag: "🇫🇯" },
  { name: "Filipinas", flag: "🇵🇭" },
  { name: "Finlândia", flag: "🇫🇮" },
  { name: "França", flag: "🇫🇷" },
  { name: "Gabão", flag: "🇬🇦" },
  { name: "Gâmbia", flag: "🇬🇲" },
  { name: "Gana", flag: "🇬🇭" },
  { name: "Geórgia", flag: "🇬🇪" },
  { name: "Granada", flag: "🇬🇩" },
  { name: "Grécia", flag: "🇬🇷" },
  { name: "Guatemala", flag: "🇬🇹" },
  { name: "Guiana", flag: "🇬🇾" },
  { name: "Guiné", flag: "🇬🇳" },
  { name: "Guiné-Bissau", flag: "🇬🇼" },
  { name: "Guiné Equatorial", flag: "🇬🇶" },
  { name: "Haiti", flag: "🇭🇹" },
  { name: "Honduras", flag: "🇭🇳" },
  { name: "Hungria", flag: "🇭🇺" },
  { name: "Iêmen", flag: "🇾🇪" },
  { name: "Ilhas Cook", flag: "🇨🇰" },
  { name: "Ilhas Marshall", flag: "🇲🇭" },
  { name: "Ilhas Salomão", flag: "🇸🇧" },
  { name: "Índia", flag: "🇮🇳" },
  { name: "Indonésia", flag: "🇮🇩" },
  { name: "Irã", flag: "🇮🇷" },
  { name: "Iraque", flag: "🇮🇶" },
  { name: "Irlanda", flag: "🇮🇪" },
  { name: "Islândia", flag: "🇮🇸" },
  { name: "Israel", flag: "🇮🇱" },
  { name: "Itália", flag: "🇮🇹" },
  { name: "Jamaica", flag: "🇯🇲" },
  { name: "Japão", flag: "🇯🇵" },
  { name: "Jordânia", flag: "🇯🇴" },
  { name: "Kiribati", flag: "🇰🇮" },
  { name: "Kuwait", flag: "🇰🇼" },
  { name: "Laos", flag: "🇱🇦" },
  { name: "Lesoto", flag: "🇱🇸" },
  { name: "Letônia", flag: "🇱🇻" },
  { name: "Líbano", flag: "🇱🇧" },
  { name: "Libéria", flag: "🇱🇷" },
  { name: "Líbia", flag: "🇱🇾" },
  { name: "Liechtenstein", flag: "🇱🇮" },
  { name: "Lituânia", flag: "🇱🇹" },
  { name: "Luxemburgo", flag: "🇱🇺" },
  { name: "Macedônia do Norte", flag: "🇲🇰" },
  { name: "Madagascar", flag: "🇲🇬" },
  { name: "Malásia", flag: "🇲🇾" },
  { name: "Malaui", flag: "🇲🇼" },
  { name: "Maldivas", flag: "🇲🇻" },
  { name: "Mali", flag: "🇲🇱" },
  { name: "Malta", flag: "🇲🇹" },
  { name: "Marrocos", flag: "🇲🇦" },
  { name: "Maurícia", flag: "🇲🇺" },
  { name: "Mauritânia", flag: "🇲🇷" },
  { name: "México", flag: "🇲🇽" },
  { name: "Mianmar", flag: "🇲🇲" },
  { name: "Micronésia", flag: "🇫🇲" },
  { name: "Moçambique", flag: "🇲🇿" },
  { name: "Moldávia", flag: "🇲🇩" },
  { name: "Mônaco", flag: "🇲🇨" },
  { name: "Mongólia", flag: "🇲🇳" },
  { name: "Montenegro", flag: "🇲🇪" },
  { name: "Namíbia", flag: "🇳🇦" },
  { name: "Nauru", flag: "🇳🇷" },
  { name: "Nepal", flag: "🇳🇵" },
  { name: "Nicarágua", flag: "🇳🇮" },
  { name: "Níger", flag: "🇳🇪" },
  { name: "Nigéria", flag: "🇳🇬" },
  { name: "Niue", flag: "🇳🇺" },
  { name: "Noruega", flag: "🇳🇴" },
  { name: "Nova Zelândia", flag: "🇳🇿" },
  { name: "Omã", flag: "🇴🇲" },
  { name: "Países Baixos", flag: "🇳🇱" },
  { name: "Palau", flag: "🇵🇼" },
  { name: "Panamá", flag: "🇵🇦" },
  { name: "Papua Nova Guiné", flag: "🇵🇬" },
  { name: "Paquistão", flag: "🇵🇰" },
  { name: "Paraguai", flag: "🇵🇾" },
  { name: "Peru", flag: "🇵🇪" },
  { name: "Polônia", flag: "🇵🇱" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Quênia", flag: "🇰🇪" },
  { name: "Quirguistão", flag: "🇰🇬" },
  { name: "Reino Unido", flag: "🇬🇧" },
  { name: "República Centro-Africana", flag: "🇨🇫" },
  { name: "República Checa", flag: "🇨🇿" },
  { name: "República do Congo", flag: "🇨🇬" },
  { name: "República Democrática do Congo", flag: "🇨🇩" },
  { name: "República Dominicana", flag: "🇩🇴" },
  { name: "Romênia", flag: "🇷🇴" },
  { name: "Ruanda", flag: "🇷🇼" },
  { name: "Rússia", flag: "🇷🇺" },
  { name: "Samoa", flag: "🇼🇸" },
  { name: "San Marino", flag: "🇸🇲" },
  { name: "Santa Lúcia", flag: "🇱🇨" },
  { name: "São Cristóvão e Neves", flag: "🇰🇳" },
  { name: "São Tomé e Príncipe", flag: "🇸🇹" },
  { name: "São Vicente e Granadinas", flag: "🇻🇨" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Serra Leoa", flag: "🇸🇱" },
  { name: "Sérvia", flag: "🇷🇸" },
  { name: "Seychelles", flag: "🇸🇨" },
  { name: "Singapura", flag: "🇸🇬" },
  { name: "Síria", flag: "🇸🇾" },
  { name: "Somália", flag: "🇸🇴" },
  { name: "Sri Lanka", flag: "🇱🇰" },
  { name: "Sudão", flag: "🇸🇩" },
  { name: "Sudão do Sul", flag: "🇸🇸" },
  { name: "Suécia", flag: "🇸🇪" },
  { name: "Suíça", flag: "🇨🇭" },
  { name: "Suriname", flag: "🇸🇷" },
  { name: "Tailândia", flag: "🇹🇭" },
  { name: "Taiwan", flag: "🇹🇼" },
  { name: "Tajiquistão", flag: "🇹🇯" },
  { name: "Tanzânia", flag: "🇹🇿" },
  { name: "Timor-Leste", flag: "🇹🇱" },
  { name: "Togo", flag: "🇹🇬" },
  { name: "Tonga", flag: "🇹🇴" },
  { name: "Trinidad e Tobago", flag: "🇹🇹" },
  { name: "Tunísia", flag: "🇹🇳" },
  { name: "Turquemenistão", flag: "🇹🇲" },
  { name: "Turquia", flag: "🇹🇷" },
  { name: "Tuvalu", flag: "🇹🇻" },
  { name: "Ucrânia", flag: "🇺🇦" },
  { name: "Uganda", flag: "🇺🇬" },
  { name: "Uruguai", flag: "🇺🇾" },
  { name: "Uzbequistão", flag: "🇺🇿" },
  { name: "Vanuatu", flag: "🇻🇺" },
  { name: "Vaticano", flag: "🇻🇦" },
  { name: "Venezuela", flag: "🇻🇪" },
  { name: "Vietnã", flag: "🇻🇳" },
  { name: "Zâmbia", flag: "🇿🇲" },
  { name: "Zimbábue", flag: "🇿🇼" }
].sort((a, b) => a.name.localeCompare(b.name, 'pt'));
